_target_: crysbfn.pl_modules.egnn.cspnet.CSPNet
hidden_dim: 512
time_dim: ${model.time_dim}
max_atoms: ${data.num_atom_types}
num_layers: 6
act_fn: silu
dis_emb: sin
num_freqs: 128
edge_style: fc
smooth: true
max_neighbors: ${model.max_neighbors}
cutoff: ${model.radius}
ln: true
ip: true
pred_type: true
period: ${model.T_max}-${model.T_min}   # 2 * np.pi
dtime_loss: ${model.BFN.dtime_loss}
add_n_atom_feat: false
cond_acc: ${model.BFN.cond_acc}