_target_: crysbfn.pl_modules.vm_bfn_plmodel.VM_BFN_PL_Model

time_dim: 128
hidden_dim: 256
latent_dim: 256
fc_num_layers: 1
max_atoms: ${data.max_atoms}
cost_natom: 1.
cost_coord: 5e-2 # 10
cost_type: 5e-2 # 1.
cost_lattice: 5e-2
cost_composition: 1.
cost_edge: 10.
cost_property: 1.
beta: 0.01
teacher_forcing_lattice: true
teacher_forcing_max_epoch: ${data.teacher_forcing_max_epoch}
max_neighbors: 20  
radius: 7.  
sigma_begin: 0.25
sigma_end: 0.01
type_sigma_begin: 5.
type_sigma_end: 0.01
num_noise_level: 50
predict_property: true
T_min: -np.pi
T_max: np.pi

BFN:
  _target_: crysbfn.pl_modules.vm_bfn.VM_BFN
  kappa1_coord: 0.02
  total_steps: 1000
  device: cuda
  beta1_type: 0.5
  beta1_coord: 1e3
  beta1_angles: 1e4
  sigma1_length: 1e-2
  K: ${data.num_atom_types}
  t_min: 1e-7
  do_zero_center_of_mass: false
  dtime_loss: true
  dtime_loss_steps: 1000
  lattice_as_6cts: false
  lattice_as_lengths_angles: ${model.BFN.lattice_as_6cts}
  sigma1_lattice: 0.03162277660168379
  mult_constant: true
  lattice_as_33: false
  pred_mean: true
  charge_loss: false
  sigma1_charge: 1e-2
  norm_loss: false
  disc_samp_flow: true
  sim_cir_flow: false
  cond_acc: false
  sch_type: exp
  
defaults:
  - decoder: cspnet
