_target_: crysbfn.pl_modules.vm_bfn_csp_plmodel.VM_BFN_CSP_PL_Model

time_dim: 128
hidden_dim: 256
latent_dim: 256
fc_num_layers: 1
max_atoms: ${data.max_atoms}
cost_natom: 1.
cost_coord: 1 # 10
cost_type: 1 # 1.
cost_lattice: 1
cost_composition: 1.
cost_edge: 10.
cost_property: 1.
beta: 0.01
teacher_forcing_lattice: true
teacher_forcing_max_epoch: ${data.teacher_forcing_max_epoch}
max_neighbors: 20  
radius: 7.  
sigma_begin: 0.5
sigma_end: 0.005
type_sigma_begin: 5.
type_sigma_end: 0.01
num_noise_level: 50
predict_property: true

T_min: -np.pi
T_max: np.pi

norm_weight: false
norm_beta: true
rej_samp: false

n_samples: 1
BFN:
  _target_: crysbfn.pl_modules.vm_bfn_csp.VM_BFN_CSP
  device: cuda
  beta1_type: 0.5
  beta1_coord: 1e3
  K: ${data.num_atom_types}
  t_min: 1e-7
  dtime_loss: true
  dtime_loss_steps: 1000
  sigma1_lattice: 0.03162277660168379
  mult_constant: true
  pred_mean: true
  end_back: true
  sim_cir_flow: true
  cond_acc: ${model.BFN.sim_cir_flow}
  sch_type: linear
  disc_prob_loss: false
  
defaults:
  - decoder: cspnet
